#version 430

layout(local_size_x = 1) in;

struct Particle {
    vec3 position;
    vec3 velocity;
    vec3 velocity2;
};

layout(std430, binding = 1) buffer ParticleBuffer2 {
    Particle rainParticles[];
};

uniform float dt;
uniform bool startTime;
uniform bool switchVelocity;


void main() {
    uint id = gl_GlobalInvocationID.x;


    vec3 pos = rainParticles[id].position;

    if (startTime) {
        vec3 dir = normalize(-rainParticles[id].position);
        pos += dir * .2;
    } 
    // pos += rainParticles[id].velocity;
    else {
        pos -= rainParticles[id].velocity;
        if (pos.y >= 120.0) pos.y = -120.0;
    }

    if (switchVelocity) {
        pos += rainParticles[id].velocity2 * 3.0;
    }

    // if (pos.y <= -40.0)
    //     pos.y = 20.0;

    rainParticles[id].position = pos;
}


