#version 430

layout(local_size_x = 1) in;

struct Particle {
    vec3 position;
    vec3 velocity;
};

layout(std430, binding = 0) buffer ParticleBuffer2 {
    Particle rainParticles[];
};

uniform float dt;
uniform bool startTime;
float dt2 = 2.0;


void main() {
    uint id = gl_GlobalInvocationID.x;

    float speed = startTime ? dt2 * 0.0 : 0.0;


    vec3 pos = rainParticles[id].position;

    if (startTime) pos += rainParticles[id].velocity;
    else pos -= rainParticles[id].velocity;

    // if (pos.y <= -40.0)
    //     pos.y = 20.0;

    rainParticles[id].position = pos;
}


